### ISSUE TITLE
How to use these code?

### ISSUE THREAD

**Issue by HandsomeCBX** [gw-zhong/UniMF#1]
Thank you for your work, can you tell me need I just run the code without any rectify?
bash scripts/mosi.sh [input_mdalities] [experiment_id] [number_of_trials]

**Comment by gw-zhong** [comment]
Thank you for your attention to our work!
Yes, after you clone our repository, you can directly run the code using bash scripts.
(If there are missing installation packages for the environment, please install them using `conda` or `pip`.)
For example, you can run the MOSI dataset in full modality mode with the following command:
`bash scripts/mosi.sh LAV 233 10`
Here, the experiment ID is specified as `233`, and `10` optimizations will be performed using Optuna.

**Comment by HandsomeCBX** [comment]
> Thank you for your attention to our work! Yes, after you clone our repository, you can directly run the code using bash scripts. (If there are missing installation packages for the environment, please install them using `conda` or `pip`.) For example, you can run the MOSI dataset in full modality mode with the following command: `bash scripts/mosi.sh LAV 233 10` Here, the experiment ID is specified as `233`, and `10` optimizations will be performed using Optuna.

I appreciate your reply. Can you provide your environment file?There is an error.Thank you vert much.
![e7ae7dee5ffb84dab9909c42eaa340a](https://github.com/gw-zhong/UniMF/assets/148057185/e4575f3b-d444-4421-bfd1-307c3ef3da48)

**Comment by gw-zhong** [comment]
Of course! Thank you for your advice. We have exported the environment dependency packages as `requirements.txt` and uploaded it to the repository.  Please check it.

**Comment by HandsomeCBX** [comment]
> Of course! Thank you for your advice. We have exported the environment dependency packages as `requirements.txt` and uploaded it to the repository. Please check it.

Thank you very much,I have built the environment.But when I run the code you give it to me,there is an error.
![378508e099a4faf93836de0f1708196](https://github.com/gw-zhong/UniMF/assets/148057185/5667a284-0590-4b38-9a27-0b699326f907)

**Comment by gw-zhong** [comment]
We are very sorry that due to our negligence, we forgot to change `datapath` in `main.py` to `data`.  You can replace
`parser.add_argument('--data_path', type=str, default='/root/autodl-tmp', help='path for storing the dataset')`
with:
`parser.add_argument('--data_path', type=str, default='data', help='path for storing the dataset')`
We apologize for any inconvenience caused to you. Can you try to run it now?

**Comment by HandsomeCBX** [comment]
> We are very sorry that due to our negligence, we forgot to change `datapath` in `main.py` to `data`. You can replace `parser.add_argument('--data_path', type=str, default='/root/autodl-tmp', help='path for storing the dataset')` with: `parser.add_argument('--data_path', type=str, default='data', help='path for storing the dataset')` We apologize for any inconvenience caused to you. Can you try to run it now?

I appreciate your work,but there is no the file named mosi aligned  LAV UniMF.pt in your riginal datasets.
![17c929937e8c735e2aaf43ec6821e64](https://github.com/gw-zhong/UniMF/assets/148057185/2b7764f0-9533-4583-b1b9-a944245073d2)

**Comment by gw-zhong** [comment]
`mosi_aligned_LAV_UniMF.pt` is the model saved during training, you can check to see if the folders `data`, `results` and `pre_trained_models` were correctly created.

**Comment by HandsomeCBX** [comment]
> `mosi_aligned_LAV_UniMF.pt` is the model saved during training, you can check to see if the folders `data`, `results` and `pre_trained_models` were correctly created.

Thank you very much, I am sorry about my negligence.It is working.

**Comment by HandsomeCBX** [comment]
> `mosi_aligned_LAV_UniMF.pt` is the model saved during training, you can check to see if the folders `data`, `results` and `pre_trained_models` were correctly created.

If I want to train the mosei datas, it is like the code mosi?

**Comment by gw-zhong** [comment]
Yes, you can use the corresponding bash script, or use the original python command line custom parameters for training.

**Comment by HandsomeCBX** [comment]
> Yes, you can use the corresponding bash script, or use the original python command line custom parameters for training.

Thank you,哥们，你太牛逼了！

**Comment by gw-zhong** [comment]
谢谢你支持我们的工作:)

**Comment by HandsomeCBX** [comment]
> 谢谢你支持我们的工作:)

哥们，我还有个问题，就是我可以自己加一个模型进去进行测试吗？

**Comment by gw-zhong** [comment]
当然可以，你可以在`model.py`里加入自己的模型，然后对`train.py`进行修改或者新建一个自己的train文件，就可以在数据集上测试自己的模型

**Comment by HandsomeCBX** [comment]
> 当然可以，你可以在`model.py`里加入自己的模型，然后对`train.py`进行修改或者新建一个自己的train文件，就可以在数据集上测试自己的模型

但是我不知道是不是适配的，你知道有哪个网站是可以找得到一些model.py的吗，我先做些测试，非常感谢！

**Comment by gw-zhong** [comment]
我的论文代码是基于这篇[ACL2019]MulT进行修改的，你可以进行参考：
https://github.com/yaohungt/Multimodal-Transformer
其它也有[EMNLP2021]SPT的文章也是基于上面这个仓库进行修改的，你也可以参考一下：
https://github.com/chengjunyan1/SP-Transformer

**Comment by HandsomeCBX** [comment]
> 我的论文代码是基于这篇[ACL2019]MulT进行修改的，你可以进行参考： https://github.com/yaohungt/Multimodal-Transformer 其它也有[EMNLP2021]SPT的文章也是基于上面这个仓库进行修改的，你也可以参考一下： https://github.com/chengjunyan1/SP-Transformer

好的，非常感谢！
