### ISSUE TITLE
Inquire about the visualization of Figure 6 in the article

### ISSUE THREAD

**Issue by JunsFu** [gw-zhong/UniMF#2]
![image](https://github.com/gw-zhong/UniMF/assets/100461491/dd5aaaee-3285-40b9-91dd-df1d3b1876cc)
Hello, thank you for your hard work and dedication!

I have a question: Is the data of these T-SNE visualization images in Figure 6 a joint representation vector?
If so, is it the part I circled in red in Figure 2? If not, what is that?

Thank you for your answer!
![image](https://github.com/gw-zhong/UniMF/assets/100461491/3d9a9b7b-14f9-45d4-845b-ec0d6d45a296)

**Comment by gw-zhong** [comment]
Thank you very much for your interest in our work. As you said, Figure 6 shows the t-SNE scatterplot of the joint representation vector, that is, the representation of the network before it passes through the last fully connected layer. Mathematically, it is:
$y=\text{classifier}(h),$
if $y \in \mathbb{R}^1$ represents the sentiment regression value, then $h \in \mathbb{R}^{hidden}$ is the vector we are using to plot the scatterplot.

**Comment by JunsFu** [comment]
Thank you very much for your timely answer. I have understood the problem!
